version: '3.3'
services:
  rabbit:
    image: rabbitmq:3.6.11-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      NAME: "rabbit"